tapas: Patch IMS app | OS2.0.207.0.VMTMIXM
Issue:
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.codeaurora.ims, PID: 28211
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of:
Landroid/telephony/TelephonyBaseUtilsStub;
E AndroidRuntime:       at
org.codeaurora.ims.ImsServiceStateReceiver.updateHDIcon(ImsServiceStateReceiver.java:68)
E AndroidRuntime:       at
org.codeaurora.ims.ImsServiceSub.<init>(ImsServiceSub.java:327)
E AndroidRuntime:       at
org.codeaurora.ims.ImsSubController.createImsServiceSub(ImsSubController.java:237)
E AndroidRuntime:       at
org.codeaurora.ims.ImsSubController.<init>(ImsSubController.java:201)
E AndroidRuntime:       at
org.codeaurora.ims.ImsSubController.<init>(ImsSubController.java:192)
E AndroidRuntime:       at
org.codeaurora.ims.ImsService.setup(ImsService.java:41)
E AndroidRuntime:       at
org.codeaurora.ims.ImsService.onCreate(ImsService.java:71)
E AndroidRuntime:       at
android.app.ActivityThread.handleCreateService(ActivityThread.java:4486)
E AndroidRuntime:       at
android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown
Source:0)
E AndroidRuntime:       at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
E AndroidRuntime:       at
android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:       at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime:       at
android.app.ActivityThread.main(ActivityThread.java:7913)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native
Method)
E AndroidRuntime:       at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
E AndroidRuntime:       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException:
android.telephony.TelephonyBaseUtilsStub
E AndroidRuntime:       ... 17 more

Solution:
Patched to remove com.qti.permission.BIND_QTI_IMS_SERVICE and
Landroid/telephony/TelephonyBaseUtilsStub;->isMiuiRom()

Patch:
https://paste.myself5.de/zitiketuto.diff